version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: vulnb0x-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=strongpassword11
  redis:
    image: 'redis:6.2-alpine'
    command: redis-server --requirepass strongpassword
    ports:
      - '6379:6379'
  vulnb0x:
    pirvileged: true
    build: ./main-app
    depends_on:
      - mongodb
    container_name: vulnb0x-app
    ports:
      - "8090:8090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock