version: '3'
services:
  docker:
    hostname: vulnb0x-docker
    domainname: vulnb0x-docker
    image: docker:dind
    privileged: yes
    container_name: vulnb0x-docker
    volumes:
      - certs:/certs/client
      - repositories:/var/repositories
  mongodb:
    image: mongo:latest
    restart: always
    container_name: vulnb0x-mongodb
    hostname: vulnb0x-mongodb
    domainname: vulnb0x-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=strongpassword11
  vulnb0x:
    build: ./main-app
    depends_on:
      - mongodb
      - docker
    container_name: vulnb0x-app 
    environment:
      - APP_PORT=8090
      - REPOS_PATH=/var/repositories
      - MONGO_URL=mongodb://user:strongpassword11@vulnb0x-mongodb:27017/
      - MONGO_DB=prod
      - DOCKER_HOST=tcp://vulnb0x-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - certs:/certs/client
      - repositories:/var/repositories
      - ./privkey/id_rsa:/var/data/privkey
    ports:
      - "8090:8090"
volumes:
  certs:
  repositories: