Vagrant.configure("2") do |config|
    config.vm.define "vulnb0x" do |box|
        box.vm.provider "hyperv" do |p|
            p.memory = 4096
            p.cpus = 4
        end

        box.vm.provider "vmware_esxi" do |p|
            p.guest_memsize=4096
            p.guest_numvcpus=2
            p.esxi_hostname = 'esxi.alf'
            p.esxi_username = 'root'
            p.esxi_password = 'prompt:'
    
        end

        box.vm.hostname = "vulnb0x"
        box.vm.box = "generic/debian10"

        box.vm.synced_folder "./", "/app/vulnb0x"

        box.vm.provision :shell, path: "vagrant-scripts/install_dependencies.sh"
    end

end